### ISSUE TITLE
Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime

### ISSUE THREAD

**Issue by SebghatYusuf** [Manu311/dart-php_serializer#1]
Hello, After adding this package to my pubspec.yaml file I was not able to run app. I just got a white screen and the above error. 
can you please confirm is the issue from this package or not: 
I just checked when I add the package even when the app is running in Debug mode, and installing the package still I get this error: 
E/flutter (27283): [ERROR:flutter/shell/common/shell.cc(242)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
E/flutter (27283): [ERROR:flutter/runtime/dart_isolate.cc(169)] Could not prepare isolate.
E/flutter (27283): [ERROR:flutter/runtime/runtime_controller.cc(401)] Could not create root isolate.

Here is the dependencies I'm using:
dependencies:
  flutter:
    sdk: flutter
  flutter_icons:
    git:
      url: git://github.com/SebghatYusuf/flutter-icons.git
      ref: null-safety-migration
  camera: ^0.8.1+1
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  dart_ipify: ^1.1.0
  dotted_border: ^2.0.0
  email_validator: ^2.0.1
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_performance: ^0.7.0+3
  flutter_credit_card: ^2.0.0
  flutter_dotenv: ^5.0.0
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  google_ml_kit: ^0.5.1
  http: ^0.13.3
  image_picker: ^0.8.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  stripe_payment: ^1.1.1
  php_serializer: ^0.3.0

**Comment by Manu311** [comment]
Hello @SebghatYusuf ,
thanks for reporting that! I guess I was too ambitious when I added the `UsePropertiesOnMissingSerializationInformation` implementation.
It was meant as a comfortable feature which could create source-code for you, but apparently I failed to prevent it from being included on not supported systems :disappointed: .
I'll try to improve that when I have time, for the moment you should be able to downgrade to "^0.2.0" which doesn't have this class yet.

**Comment by Manu311** [comment]
This should be fixed in 0.3.1 (and 1.0.0-pre.2) now.
