### ISSUE TITLE
Some last characters are lost when deserialize

### ISSUE THREAD

**Issue by gtu-myowin** [Manu311/dart-php_serializer#2]
The original serialize string is `a:1:{s:4:"acre";s:29:"50’x70’x80’ how are you";}` but after passing it to `phpDeserialize()` function, it returns `{acre: 50’x70’x80’ how are }`. As you can see ` you` is removed by the function. Is that a bug or me that cause the issue?

**Comment by Manu311** [comment]
I can reproduce the different behavior compared to Php, so this definitely is a bug.
I'll add a test and try to fix it asap. Thanks for reporting!

**Comment by Manu311** [comment]
Should be fixed now.
I added your example to the test-cases and fixed the issue with code I had already lying around but didn't deploy since it didn't seem to behave differently, but in your example-case does and is indeed the correct solution.

**Comment by gtu-myowin** [comment]
Thank you for the handy package and the fix. I will check it and let you know if it is fixed.
